# Generated by Django 5.2 on 2025-05-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pdf_summary",
            field=models.TextField(
                blank=True,
                help_text="HuggingFace AI ile oluşturulan PDF/metin özeti",
                null=True,
            ),
        ),
    ]
